FieldOfficerManagment/urls.py
from django.urls import re_path as url
from django.contrib import admin
from . import views

app_name = 'FieldOfficerManagment'

urlpatterns = [
    url(r'^$', views.fieldOfficerDispachedList, name='index'),
    url(r'^create_Dispatch/$', views.create_Dispatch, name='create_Dispatch'),
    url(r'^getPoliceOfficer/(?P<policeStationName>[a-zA-Z ]+)/$', views.getPoliceOfficer, name='getPoliceOfficer'),
    url(r'^getpoliceStallName/(?P<policeStationName>[a-zA-Z ]+)/$', views.getpoliceStallName, name='getpoliceStallName'),
    url(r'^getOfficersByPoliceStall/(?P<stallName>[a-zA-Z ]+)/(?P<dispachedDate>\d{4}-\d{2}-\d{2})/$', views.getOfficersByPoliceStall, name='getOfficersByPoliceStall'),
]

IncidentManagment/urls.py
from django.urls import re_path as url
from django.contrib import admin
from . import views

app_name = 'IncidentManagment'

urlpatterns = [
    url(r'^incidentList/$', views.incidentList, name='incidentList'),
    url(r'^create_Incident/$', views.create_Incident, name='create_Incident'),
    url(r'^AssignPoliceForIncident/$', views.AssignPoliceForIncident, name='AssignPoliceForIncident'),
    url(r'^AssignPoliceStallForIncident/$', views.AssignPoliceStallForIncident, name='AssignPoliceStallForIncident'),
]

IncidentManagmentSystem/urls.py
from django.urls import re_path as url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('FieldOfficerManagment.urls')),
    url(r'^', include('IncidentManagment.urls')),
    url(r'^', include('user.urls'))
]

user/urls.py
from django.urls import path
from user import views as user_view
from django.contrib.auth import views as auth
from .views import RegistrationView, LoginView, LogoutView,ChangePasswordView
from rest_framework_simplejwt import views as jwt_views

app_name = 'user'

urlpatterns = [
    path('accounts/register', RegistrationView.as_view(), name='register'),
    path('accounts/login', LoginView.as_view(), name='register'),
    path('accounts/logout', LogoutView.as_view(), name='register'),
    path('accounts/change-password', ChangePasswordView.as_view(), name='register'),
    path('accounts/token-refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', user_view.Login, name ='login'),
    path('logout/', auth.LogoutView.as_view(template_name ='IncidentManagment/Incident_List.html'), name ='logout'),
]

FieldOfficerManagment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime



STATUS_CHOICES = (
    ("Ready", "Ready"),
    ("OnDuty", "OnDuty"),
    ("offDuty", "offDuty"),
)


class FieldOfficer(models.Model):
    firstName = models.CharField(max_length=250)
    lastName = models.CharField(max_length=250)
    phoneNumber = models.CharField(max_length=20)
    policeStation = models.CharField(max_length=250)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES,default = 'Ready')


    def __str__(self):
        return self.firstName + '-' + self.lastName


class FieldOfficerDispatch(models.Model):
    fieldOfficer = models.ForeignKey(FieldOfficer, on_delete=models.CASCADE)
    dispatchedDate = models.DateField()
    policeStallName = models.CharField(max_length=250)

    def __str__(self):
        return self.policeStallName

FieldOfficerManagment/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import FieldOfficer, FieldOfficerDispatch
from django.conf import settings


class FieldOfficerForm(forms.ModelForm):

    class Meta:
        model = FieldOfficer
        fields = ['firstName', 'lastName', 'phoneNumber', 'policeStation' ,'status']


class FieldOfficerDispatchForm(forms.ModelForm):
    dispatchedDate = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y'), input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = FieldOfficerDispatch
        fields = ['fieldOfficer','dispatchedDate', 'policeStallName']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

FieldOfficerManagment/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import JsonResponse

from django.shortcuts import HttpResponse, get_object_or_404

from django.shortcuts import render
from geoserver.catalog import Catalog
import pg8000, json
# Create your views here.
from FieldOfficerManagment.forms import FieldOfficerDispatchForm, FieldOfficerForm
from FieldOfficerManagment.models import FieldOfficer, FieldOfficerDispatch
from django.core.serializers.json import DjangoJSONEncoder


def fieldOfficerDispachedList(request):
    cat = Catalog("http://localhost:8083/geoserver/rest/", username="admin", password="geoserver")
    lay1 = cat.get_layer("nfs_boundary")



    context = {
        "lay1": lay1
    }
    return render(request, 'FieldOfficerManagment/fieldOfficerDispachedList.html', context)

def create_Dispatch(request):

        conn = pg8000.connect(database="IncidentManagmentDb", user="postgres",password="postgres")
        cursor = conn.cursor()
        cursor.execute("Select name,gid from nfs_policestations")
        results = cursor.fetchall()
        policeStationList=[]

        for row in results:
            pname, gid=row
            slDict={}
            slDict['policeStation'] = pname
            slDict['gid'] = gid

            policeStationList.append(slDict)


        cat = Catalog("http://localhost:8083/geoserver/rest/", username="admin", password="geoserver")
        lay1 = cat.get_layer("nfs_boundary")


        form = FieldOfficerDispatchForm(request.POST or None, request.FILES or None)
        if form.is_valid():
                dispatch = form.save(commit=False)
                dispatch.save()

                field_officer_id=form.cleaned_data["fieldOfficer"].id
                field_officer=FieldOfficer.objects.get(id=field_officer_id)
                field_officer.status = "OnDuty"
                field_officer.save()




        context = {
            "form": form,
            "lay1": lay1,
            "policeStationList":policeStationList


        }
        return render(request, 'FieldOfficerManagment/CreateFieldOfficerDispach.html', context)


##views.py
def getPoliceOfficer(request,policeStationName):
    offcerList= FieldOfficer.objects.filter(policeStation=policeStationName, status='Ready').values('id', 'firstName','lastName')
    data =json.dumps(list(offcerList))
    return JsonResponse(data,safe=False)

##views.py
def getpoliceStallName(request,policeStationName):
    conn = pg8000.connect(database="IncidentManagmentDb", user="postgres",password="postgres")
    cursor = conn.cursor()
    cursor.execute("Select stallname from nfs_policestalls where stationnam='" + policeStationName + "'")
    stallList = cursor.fetchall()
    data =json.dumps(list(stallList))

    return JsonResponse(data,safe=False)


##views.py
def getOfficersByPoliceStall(request,stallName, dispachedDate):
    offcerList= FieldOfficer.objects.filter(fieldofficerdispatch__policeStallName=stallName,fieldofficerdispatch__dispatchedDate=dispachedDate).values('id', 'firstName','lastName','phoneNumber')
    data =json.dumps(list(offcerList))
    return JsonResponse(data,safe=False)

FieldOfficerManagment/templates/FieldOfficerManagment/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
      <link rel="stylesheet" href="{% static 'FieldOfficerManagment/css/bootstrap.min.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'FieldOfficerManagment/css/style.css' %}"/>
 <link rel="stylesheet" type="text/css" href="{% static 'FieldOfficerManagment/css/jquery-ui.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

     <script src="{% static 'FieldOfficerManagment/js/bootstrap.min.js' %} "></script>

     <script src="{% static 'FieldOfficerManagment/js/jquery-1.12.4.js' %} "></script>
     <script src="{% static 'FieldOfficerManagment/js/jquery-ui.js' %} "></script>


    <script src="{% static 'FieldOfficerManagment/js/main.js' %}"></script>



</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'FieldOfficerManagment:index' %}">Viberr</a>
            <a class="navbar-brand" href="{% url 'FieldOfficerManagment:map_display' %}">Display Map</a>
            <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'FieldOfficerManagment:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'FieldOfficerManagment:songs' 'all' %}"><span class="glyphicon glyphicon-FieldOfficerManagment" aria-hidden="true"></span>&nbsp; Songs</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'FieldOfficerManagment:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'FieldOfficerManagment:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'FieldOfficerManagment:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

FieldOfficerManagment/templates/FieldOfficerManagment/base_map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'FieldOfficerManagment/css/bootstrap.min.css' %}">
     <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="{% static 'FieldOfficerManagment/css/style.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'FieldOfficerManagment/css/jquery-ui.css' %}"/>
    <script src="{% static 'FieldOfficerManagment/js/jquery.min.js' %}"></script>
     <script src="{% static 'FieldOfficerManagment/js/bootstrap.min.js' %} "></script>
     <script src="{% static 'FieldOfficerManagment/js/main.js' %}"></script>
     <link rel="stylesheet" href="{% static 'FieldOfficerManagment/css/ol.css' %}" type="text/css">

    <script src="{% static 'FieldOfficerManagment/js/jquery-1.12.4.js' %} "></script>
     <script src="{% static 'FieldOfficerManagment/js/jquery-ui.js' %} "></script>
     <script src="{% static 'FieldOfficerManagment/js/ol.js' %}" type="text/javascript"></script>
<script>
 $(function () {
     $(".datefield" ).datepicker({
        dateFormat : 'dd/mm/yy',
        defaultDate: new Date()
    });
            $(".datefield").datepicker('setDate',new Date());

     $(".datefield").datepicker();
        });
</script>
{% block header %}
{% endblock %}
</head>
<body>
<nav class="navbar">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div>
            <a class="navbar-brand" href="{% url 'FieldOfficerManagment:index' %}"><img src="{% static 'FieldOfficerManagment/images/logo1.jpg' %} "><span>IMS</span></a>
            </div>    
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'FieldOfficerManagment:index' %}">Dispatched Officer</a></li>
                <li><a href="{% url 'IncidentManagment:incidentList' %}">Show Incidents</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'FieldOfficerManagment:create_Dispatch' %}">Prepare Dispatch</a></li>
                <li><a href="{% url 'IncidentManagment:create_Incident' %}">Add Incident</a></li>
                {% endif %}
            </ul>                      
            
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url "user:logout" %}">Logout</a></li>
                {% else %}
                <li><a href="{% url "user:login" %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

FieldOfficerManagment/templates/FieldOfficerManagment/fieldOfficerDispachedList.html
{% extends 'FieldOfficerManagment/base_map.html' %}
{% block title %}Display map{% endblock %}
{% block header %}

     <style>
      .ol-popup {
        position: absolute;
        background-color: white;
        -webkit-filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
        filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #cccccc;
        bottom: 12px;
        left: -50px;
        min-width: 280px;
      }
      .ol-popup:after, .ol-popup:before {
        top: 100%;
        border: solid transparent;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
      }
      .ol-popup:after {
        border-top-color: white;
        border-width: 10px;
        left: 48px;
        margin-left: -10px;
      }
      .ol-popup:before {
        border-top-color: #cccccc;
        border-width: 11px;
        left: 48px;
        margin-left: -11px;
      }
      .ol-popup-closer {
        text-decoration: none;
        position: absolute;
        top: 2px;
        right: 8px;
      }
      .ol-popup-closer:after {
        content: "✖";
      }
    </style>
{% endblock %}

{% block body %}
<div class="container-fluid map-container">

    <div class="row">

         <div class="form-group col-md-6">
                    <label class="control-label col-md-4" for="fieldOfficer"><label for="id_dispatchedDate">Dispatched Date:</label></label>
                    <div class="col-md-7"><input type="text" name="dispatchedDate" required id="id_dispatchedDate" class="datefield col-md-10"/></div>
            </div>
        <div class="col-sm-12">
          <button id="clear">clear</button>
            <div id="map" class="map"></div>
            <div id="popup" class="ol-popup">
              <a href="#" id="popup-closer" class="ol-popup-closer"></a>
              <div id="popup-content"></div>
            </div>

             <div id="wrapper">
                <div id="location"></div>
                <div id="scale"></div>
            </div>

            <div id="nodelist" class="col-sm-12">
                <em>Click on the map to get feature info</em>
            </div>
        </div>
   </div>
</div>
    <script type="text/javascript">

      var vectorPoliceStall=null;
      var pureCoverage = false;
      // if this is just a coverage or a group of them, disable a few items,
      // and default to jpeg format
      var format = 'image/png';
      var bounds =  [38.6795654296875, 8.90046215057373,
                    38.7780685424805, 9.00061702728271];

	  var mousePositionControl = new ol.control.MousePosition({
        className: 'custom-mouse-position',
        target: document.getElementById('location'),
        coordinateFormat: ol.coordinate.createStringXY(5),
        undefinedHTML: '&nbsp;'
      });
      var tiled = new ol.layer.Tile({

        source: new ol.source.TileWMS({
          url: 'http://localhost:8083/geoserver/IMS/wms',
          params: {'FORMAT': format,
                   'VERSION': '1.1.1',
                   tiled: true,
                LAYERS: 'IMS:{{ lay1.name }}',
                STYLES: ''

          }
        })
      });
    var vectorWorda = new ol.layer.Vector({
        source: new ol.source.Vector({

              url: 'http://localhost:8083/geoserver/IMS/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=IMS:nfs_woredas&outputFormat=application/json',
             format: new ol.format.GeoJSON()

            }),
        style: new ol.style.Style({
                stroke: new ol.style.Stroke({
                    color: '#000000',
                    width: 2
                }),
                fill: new ol.style.Fill({
                   color: 'transparent'
                })
            })

         });


      var vector = new ol.layer.Vector({
        source: new ol.source.Vector({

              url: 'http://localhost:8083/geoserver/IMS/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=IMS:nfs_policestations&outputFormat=application/json',
             format: new ol.format.GeoJSON()

           }),
        style: new ol.style.Style({

                image: new ol.style.Circle({
                    radius: 8,
                    fill: new ol.style.Fill({
                        color: 'red'
                    })
                })
            })
    });


    vectorPoliceStall = new ol.layer.Vector({
        source: new ol.source.Vector({

              url: 'http://localhost:8083/geoserver/IMS/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=IMS:nfs_policestalls&outputFormat=application%2Fjson' ,
             format: new ol.format.GeoJSON()

            }),
        style: new ol.style.Style({

                image: new ol.style.Circle({
                    radius: 6,
                    fill: new ol.style.Fill({
                        color: 'blue'
                    })
                })
            })

        });



      var projection = new ol.proj.Projection({
          code: 'EPSG:4326',
          units: 'degrees',
          axisOrientation: 'neu'
      });


       var osmLayer=new ol.layer.Tile({
            source: new ol.source.OSM()
          });

       var tiledRoads = new ol.layer.Tile({
        visible: true,
        source: new ol.source.TileWMS({
          url: 'http://localhost:8083/geoserver/IMS/wms',
          params: {'FORMAT': format,
                   'VERSION': '1.1.1',
                   tiled: true,
                STYLES: '',
                LAYERS: 'IMS:road_line_v6'
          }
        })
      });

      var vectorPoliceStallSource=new ol.source.Vector({

        url: 'http://localhost:8083/geoserver/IMS/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=IMS:nfs_policestalls&outputFormat=application%2Fjson' ,
       format: new ol.format.GeoJSON()

      });
      vectorPoliceStall = new ol.layer.Vector({
        source: vectorPoliceStallSource,
        style: new ol.style.Style({

                image: new ol.style.Circle({
                    radius: 6,
                    fill: new ol.style.Fill({
                        color: 'blue'
                    })
                })
            })

        });

        var map = new ol.Map({
          controls: ol.control.defaults({attribution: false}).extend([mousePositionControl]),
          target: 'map',
          layers: [osmLayer,tiled,tiledRoads,vectorWorda,vector,vectorPoliceStall],

          view: new ol.View({
           projection: projection
        })
      });


    /**
       * Elements that make up the popup.
       */
      var container = document.getElementById('popup');
      var content = document.getElementById('popup-content');
      var closer = document.getElementById('popup-closer');

      /**
       * Create an overlay to anchor the popup to the map.
       */
      var overlay = new ol.Overlay(/** @type {olx.OverlayOptions} */ ({
        element: container,
        autoPan: true,
        autoPanAnimation: {
          duration: 250
        }
      }));


      /**
       * Add a click handler to hide the popup.
       * @return {boolean} Don't follow the href.
       */
      closer.onclick = function() {
        overlay.setPosition(undefined);
        closer.blur();
        return false;
      };

      map.addOverlay(overlay);

      var params = {
        LAYERS: 'IMS:routing_dir',
        FORMAT: 'image/png',
        'VERSION': '1.3.0'
       };


  // The "start" and "destination" features.
  var startPoint = new ol.Feature();
  var destPoint = new ol.Feature();

  // The vector layer used to display the "start" and "destination" features.
  var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
      features: [startPoint,destPoint]
    }),
    style: new ol.style.Style({

      image: new ol.style.Circle({
          radius: 3,
          fill: new ol.style.Fill({
              color: 'yellow'
          })
      })
  })
  });

  map.addLayer(vectorLayer);

      map.getView().on('change:resolution', function(evt) {
        var resolution = evt.target.get('resolution');
        var units = map.getView().getProjection().getUnits();
        var dpi = 25.4 / 0.28;
        var mpu = ol.proj.METERS_PER_UNIT[units];
        var scale = resolution * mpu * 39.37 * dpi;
        if (scale >= 9500 && scale <= 950000) {
          scale = Math.round(scale / 1000) + "K";
        } else if (scale >= 950000) {
          scale = Math.round(scale / 1000000) + "M";
        } else {
          scale = Math.round(scale);
        }
        document.getElementById('scale').innerHTML = "Scale = 1 : " + scale;
      });
      map.getView().fit(bounds, map.getSize());
      map.on('singleclick', function(evt) {
        if (startPoint.getGeometry() == null) {
          // First click.
          startPoint.setGeometry(new ol.geom.Point(evt.coordinate));
        } else if (destPoint.getGeometry() == null) {
          // Second click.
          destPoint.setGeometry(new ol.geom.Point(evt.coordinate));
          // Transform the coordinates from the map projection (EPSG:3857)
          // to the server projection (EPSG:4326).
          var startCoord = startPoint.getGeometry().getCoordinates();
          var destCoord = destPoint.getGeometry().getCoordinates();
          var viewparams = [
            'x1:' + startCoord[0], 'y1:' + startCoord[1],
            'x2:' + destCoord[0], 'y2:' + destCoord[1]
          ];
          params.viewparams = viewparams.join(';');
          result = new ol.layer.Image({
            source: new ol.source.ImageWMS({
              url: 'http://localhost:8083/geoserver/IMS/wms',
              params: params
            })
          });
          map.addLayer(result);
        }

        document.getElementById('nodelist').innerHTML = "Loading... please wait...";
        var view = map.getView();
        var viewResolution = view.getResolution();
        var source =tiled.getSource();
        var url = source.getGetFeatureInfoUrl(
          evt.coordinate, viewResolution, view.getProjection(),
          {'INFO_FORMAT': 'text/html', 'FEATURE_COUNT': 50});
        if (url) {
          document.getElementById('nodelist').innerHTML = '<iframe class="col-sm-12" seamless src="' + url + '"></iframe>';
        }
        var feature = map.forEachFeatureAtPixel(evt.pixel,
            function(feature) {
              return feature;
            });
        if (feature) {
            var coordinate = feature.getGeometry().getCoordinates();


        var  items = '';
        var dateValue = new Date(document.getElementById('id_dispatchedDate').value);

        var date = document.getElementById('id_dispatchedDate').value.split('/');

        var newDate =  date[2] + '-' + date[1] + '-' + date[0] ;

        $.ajax({
            url: '/getOfficersByPoliceStall/' +  feature.get('stallname') + '/' + newDate + '/',
            type: "GET",
            dataType: "JSON",

            success: function (data) {


              console.log(data)

                items = '<br/><table border=1><tr><th>No.</th><th>Officer Name</th><th>Phone Number</th></tr>';

                var json = $.parseJSON(data);

                for (var i = 0; i < json.length; i++) {
                    var number=i + 1;
                    items += "<tr><td>"+ number + "</td><td>" + json[i].firstName + " " + json[i].lastName + "</td>" + "<td>" + json[i].phoneNumber  + "</td> </tr>";
                }

                items += '</table>';

                 content.innerHTML =  items ;
            }
        });

            overlay.setPosition(coordinate);
        }

       });

       var clearButton = document.getElementById('clear');
       clearButton.addEventListener('click', function(event) {
         // Reset the "start" and "destination" features.
         startPoint.setGeometry(null);
     
         // Remove the result layer.
         map.removeLayer(result);
       });
    </script>

{% endblock %}

FieldOfficerManagment/templates/FieldOfficerManagment/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="fieldOfficer">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}